# Generated by Django 5.0.2 on 2024-03-03 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name': 'Актеры и режиссеры', 'verbose_name_plural': 'Актеры и режиссеры'},
        ),
        migrations.AlterField(
            model_name='movie',
            name='world_premiere',
            field=models.DateField(default=datetime.date(2024, 3, 4), verbose_name='Премьера'),
        ),
    ]
